import { chromium } from '@playwright/test'
import { mkdirSync,writeFileSync } from 'node:fs'
mkdirSync('docs/screenshots',{recursive:true})
const browser=await chromium.launch({executablePath:'C:/Users/kouta/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']})
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1})
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())})
await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'})
await page.locator('.canvas-status').waitFor({state:'hidden',timeout:30000})
await page.screenshot({path:'docs/screenshots/workshop-desktop.png',fullPage:true})
console.log('Workshop',await page.title(),await page.locator('canvas').count(),'canvases',await page.locator('.part-card').count(),'parts')
await page.getByRole('button',{name:'鉛筆ランスを装備',exact:true}).click()
await page.getByRole('heading',{name:'どちらのパーツと交換する？'}).waitFor()
await page.locator('.replacement-list button').first().click()
await page.getByRole('button',{name:'この機体であそぶ'}).click()
await page.getByText('最初の手番',{exact:true}).locator('select').selectOption('0')
await page.getByRole('button',{name:'CPUと対戦をはじめる'}).click()
await page.locator('.canvas-status').waitFor({state:'hidden',timeout:30000})
await page.screenshot({path:'docs/screenshots/battle-desktop.png'})
console.log('Battle ready',await page.locator('.turn-banner').innerText())
await page.getByRole('button',{name:'弾く',exact:true}).click()
await page.waitForTimeout(16000)
console.log('Battle after shot',await page.locator('.turn-banner').allTextContents(),await page.locator('.result-card').allTextContents())
await page.screenshot({path:'docs/screenshots/battle-after-shot.png'})
await page.getByRole('button',{name:'一時停止',exact:true}).click()
await page.getByRole('button',{name:'この状態を保存',exact:true}).click()
console.log('Saved',await page.evaluate(()=>!!localStorage.getItem('keshibato.v1.battle')))
await page.getByRole('button',{name:'保存してメニューへ',exact:true}).click()
await page.getByRole('button',{name:'続きからあそぶ',exact:true}).click()
await page.locator('.canvas-status').waitFor({state:'hidden',timeout:30000})
console.log('Resumed saved match',await page.locator('.pause-card').count())
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1})
await mobile.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});await mobile.locator('.canvas-status').waitFor({state:'hidden',timeout:30000});await mobile.screenshot({path:'docs/screenshots/workshop-mobile.png',fullPage:true});console.log('Mobile horizontal overflow',await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth))
console.log('Errors',JSON.stringify(errors));writeFileSync('docs/screenshots/browser-errors.json',JSON.stringify(errors,null,2));await browser.close()
