import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Pause, Play, RotateCcw, Camera, Move3d, Crosshair, Save, Undo2, X, ChevronDown, Trophy, Flag, LoaderCircle, Rewind, Eye } from 'lucide-react'
import { GameScene } from '../game/scene'
import { createPhysics } from '../game/physics'
import type { PhysicsGame } from '../game/physics'
import { chooseShot } from '../game/ai'
import { attachInput } from '../game/input'
import { audio } from '../game/audio'
import { PARTS, CHALLENGES } from '../game/catalog'
import { save, download } from '../game/storage'
import type { BattleConfig, BattleSnapshot, BattleView, GameEvent, Settings, Shot } from '../game/types'

const emptyShot:Shot={direction:{x:1,y:0,z:0},power:.55,offset:0,jump:false,strike:false,magnet:'off',chalk:false,glue:false,curve:0}
interface ReplayFrame { t:number;view:BattleView;objects:ReturnType<PhysicsGame['getObjectTransforms']> }
export function Battle({config,snapshot,settings,onExit,onRematch,onResult,onChallenge,onAdvance,advanceLabel,notify}:{config:BattleConfig;snapshot?:BattleSnapshot;settings:Settings;onExit:()=>void;onRematch:()=>void;onResult:(view:BattleView)=>void;onChallenge:(id:string)=>void;onAdvance?:()=>void;advanceLabel?:string;notify:(s:string)=>void}){
 const host=useRef<HTMLDivElement>(null),scene=useRef<GameScene|null>(null),game=useRef<PhysicsGame|null>(null),input=useRef<ReturnType<typeof attachInput>|null>(null)
 const [view,setView]=useState<BattleView|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false),[thinking,setThinking]=useState(false),[shot,setShot]=useState<Shot>({...emptyShot}),[aiming,setAiming]=useState(false),[cameraMode,setCameraMode]=useState(false),[advanced,setAdvanced]=useState(false),[showPrediction,setShowPrediction]=useState(false),[replaying,setReplaying]=useState(false),[replayPaused,setReplayPaused]=useState(false),[speed,setSpeed]=useState(1),[hasReplay,setHasReplay]=useState(false),[passDevice,setPassDevice]=useState(false),[challengeDone,setChallengeDone]=useState(false),[eventText,setEventText]=useState('')
 const refs=useRef({shot,showPrediction,thinking:false,passDevice:false,done:false,challenge:false});refs.current.shot=shot;refs.current.showPrediction=showPrediction
 const callbacks=useRef({onResult,onChallenge,notify});callbacks.current={onResult,onChallenge,notify}
 const stable=useRef<BattleSnapshot|null>(null),beforeShot=useRef<BattleSnapshot|null>(null),lastShot=useRef<Shot|null>(null),frames=useRef<ReplayFrame[]>([]),recording=useRef({time:0,ticks:0,stride:3}),playback=useRef({active:false,paused:false,speed:1,time:0}),shotEvents=useRef<GameEvent[]>([]),currentShotPlayer=useRef(0)
 const practice=config.mode==='practice'||config.mode==='custom'
 function canAim(){const state=game.current?.view();return !!state&&state.phase==='aiming'&&!config.players[state.currentPlayer].cpu&&!refs.current.thinking&&!refs.current.passDevice&&!playback.current.active}
 function updateAim(next:Shot|null){setAiming(!!next);if(next)setShot(next);const engine=game.current,state=engine?.view();if(!state||!engine)return;let prediction;if(next&&refs.current.showPrediction&&(practice||config.players[state.currentPlayer].build.equipment.some(e=>e.id==='protractor')))prediction=engine.predict(next,200);scene.current?.setAim(next,state.actors[state.currentPlayer].position,prediction)}
 function shoot(next:Shot){const engine=game.current;if(!engine||!canAim())return;fire(engine,next)}
 function fire(engine:PhysicsGame,next:Shot){beforeShot.current=engine.snapshot();currentShotPlayer.current=engine.view().currentPlayer;lastShot.current=structuredClone(next);shotEvents.current=[];frames.current=[];recording.current={time:0,ticks:0,stride:3};if(engine.shoot(next)){setHasReplay(false);setAiming(false);scene.current?.clearAim();setView(engine.view());audio.play('launch',.8)}}
 function challengeCheck(state:BattleView){if(!config.challengeId||refs.current.challenge||currentShotPlayer.current!==0)return;const challenge=CHALLENGES.find(c=>c.id===config.challengeId);if(!challenge)return;const events=shotEvents.current,own=state.actors[0],contact=events.some(e=>e.type==='collision'&&(e.player===0||e.other===0));let success=false;switch(challenge.goal){case'bank':success=state.phase==='result'&&state.winner===0&&events.some(e=>e.type==='wall'&&e.player===0)&&contact;break;case'contact':success=contact;break;case'bridge':success=!own.fallen&&own.position.x>4&&Math.abs(own.position.z)<5;break;case'jump':success=events.some(e=>e.ability==='jump'&&e.player===0)&&events.some(e=>e.type==='land'&&e.player===0)&&!own.fallen;break;case'spin':success=contact&&Math.abs(lastShot.current?.offset??0)>.2;break;case'return':success=!own.fallen&&Math.hypot(own.position.x,own.position.z)<3;break;case'win':success=state.phase==='result'&&state.winner===0;break;case'surface':success=events.some(e=>e.player===0&&['chalk','glue'].includes(e.ability??''));break}if(success){refs.current.challenge=true;setChallengeDone(true);callbacks.current.onChallenge(config.challengeId);audio.play('challenge');scene.current?.celebrate()}}
 useEffect(()=>{let alive=true,aiBusy=false,uiElapsed=0,messageElapsed=0;let engine:PhysicsGame|null=null;refs.current.done=false;refs.current.challenge=false;refs.current.passDevice=false;setChallengeDone(false);setReady(false);setError('');const renderer=new GameScene(host.current!,settings);scene.current=renderer
  async function setup(){try{const [simulation]=await Promise.all([createPhysics(config,snapshot),renderer.showBattle(config)]);engine=simulation;if(!alive){simulation.dispose();return}game.current=simulation;stable.current=simulation.snapshot();renderer.update(simulation.view());setView(simulation.view());setReady(true);input.current=attachInput(renderer,{canAim,position:()=>{const s=simulation.view();return s.actors[s.currentPlayer]?.position??null},shot:()=>refs.current.shot,onAim:updateAim,onShoot:shoot});audio.setMusic(practice?'practice':config.stage.music);audio.play('start');const state=simulation.view();setShot(s=>({...s,direction:directionToOpponent(state)}));renderer.onFrame=delta=>{
    if(playback.current.active){if(!playback.current.paused){playback.current.time+=delta*playback.current.speed;const data=frames.current;const frame=data.find(f=>f.t>=playback.current.time)??data.at(-1);if(frame){renderer.update(frame.view);renderer.updateObjects(frame.objects)}if(playback.current.time>=(data.at(-1)?.t??0))playback.current.paused=true}return}
    const events=simulation.step(delta),next=simulation.view();renderer.update(next);renderer.updateObjects(simulation.getObjectTransforms());if(next.phase==='simulating'){recording.current.time+=delta;if(++recording.current.ticks%recording.current.stride===0){frames.current.push({t:recording.current.time,view:structuredClone(next),objects:simulation.getObjectTransforms()});if(frames.current.length>1800){frames.current=frames.current.filter((_,i)=>i%2===0);recording.current.stride*=2}}}
    events.forEach(event=>{shotEvents.current.push(event);if(shotEvents.current.length>200)shotEvents.current.shift();renderer.effect(event);if(event.type!=='launch'&&event.type!=='result')audio.play(event.type==='ability'?({jump:'jump',strike:'stapler',magnet:'magnet',chalk:'chalk',glue:'glue'} as Record<string,string>)[event.ability??'']??'confirm':event.type==='collision'?(event.material==='rubber_band'?'bounce':event.material==='binder_clip'?'metal':'rubber'):event.type,Math.max(.15,event.strength??.4),(event.position?.x??0)/24)
     if(event.type==='wall'&&event.strength&&event.strength>.25){setEventText('ナイスリバウンド！');messageElapsed=0}if(event.type==='fall'){setEventText(`${config.players[event.player??0].name}、リングアウト！`);messageElapsed=0}if(event.type==='ability'){setEventText({jump:'ホップ！',strike:'カチッ！ 押し込み',chalk:'チョークの粉を置いた',glue:'のりを置いた'}[event.ability??'jump']??'パーツが反応！');messageElapsed=0}
     if(event.type==='turn'||event.type==='result'){setHasReplay(frames.current.length>1);challengeCheck(next);if(event.type==='turn'){stable.current=simulation.snapshot();if(!save('battle',stable.current))callbacks.current.notify('自動保存ができませんでした。端末の空き容量をご確認ください。');setShot(s=>({...emptyShot,direction:directionToOpponent(next),power:s.power}));if(config.mode==='local'){refs.current.passDevice=true;setPassDevice(true)}}if(event.type==='result'&&!refs.current.done){refs.current.done=true;callbacks.current.onResult(next);audio.play(next.draw?'draw':next.winner===0?'win':'lose');if(next.winner===0)renderer.celebrate()}}
    });messageElapsed+=delta;if(messageElapsed>2.5)setEventText('');uiElapsed+=delta;if(uiElapsed>.1||events.length){uiElapsed=0;setView(next)}
    if(next.phase==='aiming'&&config.players[next.currentPlayer].cpu&&!aiBusy&&!refs.current.passDevice){aiBusy=true;refs.current.thinking=true;setThinking(true);const turn=next.turn;chooseShot(simulation,config.difficulty).then(choice=>{if(!alive||simulation.disposed)return;refs.current.thinking=false;setThinking(false);const current=simulation.view();if(current.phase==='aiming'&&current.turn===turn)fire(simulation,choice)}).catch(e=>{if(alive){callbacks.current.notify(`CPUの計算を再試行してください：${String(e)}`);simulation.pause();setView(simulation.view())}}).finally(()=>{aiBusy=false;refs.current.thinking=false;if(alive)setThinking(false)})}
   }
  }catch(e){if(alive)setError(String(e))}}
  void setup();const visibility=()=>{if(document.hidden&&engine){input.current?.cancel();engine.pause();setView(engine.view());audio.suspend()}};document.addEventListener('visibilitychange',visibility)
  return()=>{alive=false;document.removeEventListener('visibilitychange',visibility);input.current?.dispose();input.current=null;engine?.dispose();renderer.dispose();game.current=null;scene.current=null}
 },[config,snapshot])
 useEffect(()=>{scene.current?.setSettings(settings)},[settings])
 function directionToOpponent(state:BattleView){const i=state.currentPlayer,a=state.actors[i],enemy=state.actors.find((p,j)=>!p.fallen&&config.players[j].team!==config.players[i].team);if(!enemy)return{x:1,y:0,z:0};const x=enemy.position.x-a.position.x,z=enemy.position.z-a.position.z,n=Math.hypot(x,z)||1;return{x:x/n,y:0,z:z/n}}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,select,textarea,button')||!canAim())return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key===' '){shoot(refs.current.shot);return}if(e.key==='Escape'){updateAim(null);return}let s={...refs.current.shot};const a=Math.atan2(s.direction.x,s.direction.z);if(e.key==='ArrowLeft'||e.key==='ArrowRight'){const angle=a+(e.key==='ArrowLeft'?.045:-.045);s.direction={x:Math.sin(angle),y:0,z:Math.cos(angle)}}else if(e.key==='ArrowUp'||e.key==='ArrowDown')s.power=Math.min(1,Math.max(.03,s.power+(e.key==='ArrowUp'?.025:-.025)));else return;updateAim(s)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[])
 function pause(){input.current?.cancel();game.current?.pause();setView(game.current?.view()??null)}
 function resume(){game.current?.resume();setView(game.current?.view()??null);audio.resume()}
 function saveNow(){if(!game.current)return;if(save('battle',game.current.snapshot()))notify('対戦をこの端末に保存しました。メニューの「続きから」で再開できます。');else notify('保存できませんでした。空き容量をご確認ください。')}
 function restoreStable(){const snapshot=practice?beforeShot.current??stable.current:stable.current;if(!snapshot||!game.current)return;game.current.restore(snapshot);game.current.resume();refs.current.done=false;setView(game.current.view());setAiming(false);scene.current?.clearAim();notify('直前の静止状態へ戻しました。')}
 function startReplay(){if(!frames.current.length)return;input.current?.cancel();scene.current?.clearAim();playback.current={active:true,paused:false,speed:1,time:0};setReplaying(true);setReplayPaused(false);setSpeed(1);scene.current?.setCameraMode(true)}
 function endReplay(){playback.current.active=false;setReplaying(false);scene.current?.setCameraMode(cameraMode);if(game.current){scene.current?.update(game.current.view());scene.current?.updateObjects(game.current.getObjectTransforms())}}
 const current=view?config.players[view.currentPlayer]:config.players[0],parts=current.build.equipment.map(e=>PARTS.find(p=>p.id===e.id)!),paused=view?.phase==='paused',result=view?.phase==='result'
 const angle=Math.atan2(shot.direction.x,shot.direction.z)*180/Math.PI
 return <section className={`battle-page ${config.stage.night?'night':''}`}>
  <div className="battle-heading"><button className="icon-button" aria-label="メニューに戻る" onClick={()=>{saveNow();onExit()}}><ArrowLeft size={21}/></button><div><span className="eyebrow">{practice?'PRACTICE FIELD':'AFTER SCHOOL ARENA'}</span><h1>{config.stage.name}</h1></div><div className="battle-tools"><button className={`icon-button ${cameraMode?'active':''}`} aria-label="カメラ操作を切り替える" title="カメラ操作" onClick={()=>{input.current?.cancel();setCameraMode(!cameraMode);scene.current?.setCameraMode(!cameraMode)}}><Move3d size={20}/></button><button className="icon-button" aria-label="写真を保存" onClick={()=>{const url=scene.current?.photo();if(url){const a=document.createElement('a');a.href=url;a.download='消しバト_対戦.png';a.click();notify('対戦の写真を保存しました。')}}}><Camera size={19}/></button><button className="icon-button" aria-label="対戦を保存" onClick={saveNow}><Save size={19}/></button><button className="button small" onClick={pause}><Pause size={16}/> 一時停止</button></div></div>
  <div className="battle-stage"><div ref={host} className="canvas-host"/>{!ready&&!error&&<div className="canvas-status"><LoaderCircle className="spin"/><span>机の上を準備しています</span></div>}{error&&<div className="canvas-status error"><p>{error}</p><button onClick={onRematch}>もう一度試す</button></div>}
   <div className="players-hud">{config.players.map((player,i)=><div className={`player-chip ${view?.currentPlayer===i?'current':''} ${view?.actors[i]?.fallen?'fallen':''}`} key={i} style={{'--player-color':player.team===0?'#299e86':'#d99554'} as React.CSSProperties}><img src={`/icons/body_${player.build.body}.png`} alt=""/><div><span>{player.cpu?'CPU':`PLAYER ${i+1}`}{view?.actors[i]?.fallen?' · 場外':''}</span><strong>{player.name}</strong><small>{player.build.equipment.map(e=>PARTS.find(p=>p.id===e.id)?.shortName).join(' + ')||'装備なし'}</small></div>{view?.currentPlayer===i&&<span className="turn-dot"/>}</div>)}</div>
   {config.challengeId&&<div className="challenge-hud"><Flag size={16}/><span>{CHALLENGES.find(c=>c.id===config.challengeId)?.description}</span>{challengeDone&&<strong>達成！</strong>}</div>}
   {eventText&&<div className="event-toast" role="status">{eventText}</div>}
   {ready&&!paused&&!result&&!replaying&&<div className="turn-banner"><span className={`status-dot ${view?.phase==='simulating'?'orange':''}`}/>{view?.phase==='simulating'?'消しゴムの動きを見守ろう':thinking?`${current.name}が考えています…`:cameraMode?'カメラ操作中 · 右上のボタンで照準に戻る':`${current.name}の番。ゆっくり狙おう。`}</div>}
   {passDevice&&!paused&&<div className="stage-overlay"><div className="result-card"><span className="eyebrow">YOUR TURN</span><h2>{current.name}の番</h2><p>端末を次のプレイヤーへ渡してください。</p><button className="button primary" onClick={()=>{refs.current.passDevice=false;setPassDevice(false)}}>交代しました <ArrowRight size={18}/></button></div></div>}
   {paused&&!replaying&&<div className="stage-overlay"><div className="pause-card"><span className="eyebrow">TAKE YOUR TIME.</span><h2>ひとやすみ。</h2><p>考える時間も、対戦の時間も、制限なし。</p><button className="button primary full" onClick={resume}><Play size={18}/> 対戦にもどる</button><button className="button full" onClick={saveNow}><Save size={17}/> この状態を保存</button><button className="button full" onClick={restoreStable}><Undo2 size={17}/> 直前の静止状態へ復旧</button><button className="text-button" onClick={onRematch}>はじめからやり直す</button><button className="text-button" onClick={()=>{saveNow();onExit()}}>保存してメニューへ</button></div></div>}
   {result&&!replaying&&<div className="stage-overlay"><div className="result-card"><span className="eyebrow">{view.draw?'ONE MORE ROUND?':'NICE GAME!'}</span><div className="result-icon"><Trophy size={42}/></div><h2>{view.draw?'引き分け！':config.mode==='local'||config.mode==='team'?`チーム${view.winner===0?'ミント':'オレンジ'}の勝利！`:view.winner===0?'きみの勝ち！':'もう一度、挑戦！'}</h2><p>{view.draw?'同じ発射で、両方ともリングアウト。':view.winner===0?'小さな文房具で、大きな一勝。':'装備や狙う角度を変えてみよう。'}</p><strong className="result-build">{config.players[0].build.name}</strong><div className="result-buttons">{onAdvance&&view.winner!==null&&<button className="button primary full" onClick={onAdvance}>{advanceLabel??'次の対戦へ'} <ArrowRight size={18}/></button>}<button className="button primary full" onClick={onRematch}><RotateCcw size={17}/> 同じ装備でもう一戦</button>{hasReplay&&<button className="button full" onClick={startReplay}><Rewind size={17}/> 決まった一手をリプレイ</button>}<button className="text-button" onClick={onExit}>メニューへもどる</button></div></div></div>}
   {replaying&&<div className="replay-controls"><span>REPLAY</span><button className="icon-button" aria-label="リプレイ一時停止" onClick={()=>{playback.current.paused=!playback.current.paused;setReplayPaused(playback.current.paused)}}>{replayPaused?<Play size={19}/>:<Pause size={19}/>}</button><button className="button small" onClick={()=>{const value=speed===1?.35:1;playback.current.speed=value;setSpeed(value)}}>{speed===1?'通常速度':'スローモーション'}</button><button className="icon-button" aria-label="最初からリプレイ" onClick={()=>{playback.current.time=0;playback.current.paused=false;setReplayPaused(false)}}><RotateCcw size={18}/></button><button className="icon-button" aria-label="リプレイを閉じる" onClick={endReplay}><X size={19}/></button></div>}
  </div>
  <div className="battle-controls"><div className="control-instruction"><div className="gesture-icon"><ArrowUpRightIcon/></div><div><strong>引っぱって、はなす。</strong><p>消しゴムから逆方向へドラッグ。長さで強さが変わる。</p></div></div><div className="power-control"><label>パワー <strong>{Math.round(shot.power*100)}<small>%</small></strong></label><input aria-label="発射の強さ" type="range" min="3" max="100" value={shot.power*100} disabled={!canAim()} onChange={e=>updateAim({...shot,power:Number(e.target.value)/100})}/></div><button className="button primary shoot-button" disabled={!canAim()||cameraMode} onClick={()=>shoot(shot)}><Crosshair size={19}/> 弾く</button><button className="icon-button" aria-label="照準をキャンセル" disabled={!aiming} onClick={()=>{input.current?.cancel();updateAim(null)}}><X size={18}/></button></div>
  <div className="battle-subcontrols"><button className="text-button" onClick={()=>setAdvanced(!advanced)}>角度・打点・パーツの能力 <ChevronDown size={15}/></button><span>矢印キーで調整 · Spaceで発射 · Escで照準解除</span><div>{(practice||config.players[view?.currentPlayer??0].build.equipment.some(e=>e.id==='protractor'))&&<label className="check-label"><input type="checkbox" checked={showPrediction} onChange={e=>{setShowPrediction(e.target.checked);refs.current.showPrediction=e.target.checked;updateAim(shot)}}/><Eye size={14}/> 予測の目安</label>}{practice&&<button className="text-button" onClick={restoreStable}><Undo2 size={15}/> 1回前へ</button>}{hasReplay&&<button className="text-button" onClick={startReplay}><Rewind size={15}/> リプレイ</button>}</div></div>
  {advanced&&<div className="advanced-controls panel"><label className="form-field">狙う角度 {Math.round(angle)}°<input type="range" min="-180" max="180" value={angle} disabled={!canAim()} onChange={e=>{const a=Number(e.target.value)*Math.PI/180;updateAim({...shot,direction:{x:Math.sin(a),y:0,z:Math.cos(a)}})}}/></label><label className="form-field">打点 {shot.offset===0?'中央':shot.offset<0?'左':'右'}<input aria-label="弾く位置" type="range" min="-1" max="1" step=".05" value={shot.offset} disabled={!canAim()} onChange={e=>updateAim({...shot,offset:Number(e.target.value)})}/></label><div className="ability-controls">{parts.some(p=>p.active==='jump')&&<Ability label="ジャンプ" checked={shot.jump} disabled={!canAim()} onChange={value=>setShot({...shot,jump:value})}/>} {parts.some(p=>p.active==='strike')&&<Ability label="ホチキス押し込み" checked={shot.strike} disabled={!canAim()} onChange={value=>setShot({...shot,strike:value})}/>} {parts.some(p=>p.active==='chalk')&&<Ability label="粉を置く（最大3）" checked={shot.chalk} disabled={!canAim()} onChange={value=>setShot({...shot,chalk:value})}/>} {parts.some(p=>p.active==='glue')&&<Ability label="のりを置く（最大1）" checked={shot.glue} disabled={!canAim()} onChange={value=>setShot({...shot,glue:value})}/>} {parts.some(p=>p.active==='magnet')&&<label className="form-field">磁石<select disabled={!canAim()} value={shot.magnet} onChange={e=>setShot({...shot,magnet:e.target.value as Shot['magnet']})}><option value="off">使わない</option><option value="attract">吸引</option><option value="repel">反発</option></select></label>}{parts.some(p=>p.active==='curve')&&<label className="form-field">曲がり<input type="range" min="-1" max="1" step=".1" disabled={!canAim()} value={shot.curve} onChange={e=>setShot({...shot,curve:Number(e.target.value)})}/></label>}{!parts.some(p=>p.active)&&<p className="muted tiny">この装備は接触・重さ・摩擦で働きます。選択する能力はありません。</p>}</div></div>}
 </section>
}
function Ability({label,checked,onChange,disabled}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled:boolean}){return <label className="check-label"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} disabled={disabled}/>{label}</label>}
function ArrowUpRightIcon(){return <svg width="30" height="30" viewBox="0 0 30 30" fill="none"><path d="M8 22 23 7m0 0H13m10-6v16M8 20v5h5" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
