import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { X, RotateCcw, Scan, Box, ArrowUp, LoaderCircle } from 'lucide-react'
import { GameScene } from '../game/scene'
import type { Build, Settings } from '../game/types'

export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;dialog?.showModal();const cancel=(e:Event)=>{e.preventDefault();onClose()};dialog?.addEventListener('cancel',cancel);return()=>{dialog?.removeEventListener('cancel',cancel);dialog?.close()}},[onClose]);return <dialog ref={ref} className={`modal ${wide?'wide':''}`} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label="閉じる" onClick={onClose}><X size={20}/></button></div>{children}</dialog>}
export function Preview({build,settings,onReady,compact=false}:{build:Build;settings:Settings;onReady?:(scene:GameScene|null)=>void;compact?:boolean}){const host=useRef<HTMLDivElement>(null),scene=useRef<GameScene|null>(null);const [loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);const onReadyRef=useRef(onReady);onReadyRef.current=onReady
 useEffect(()=>{if(!host.current)return;let view:GameScene;try{view=new GameScene(host.current,settings);scene.current=view;onReadyRef.current?.(view)}catch(e){setError(`3D表示を開始できませんでした。ブラウザのハードウェア アクセラレーションを有効にしてください。${String(e)}`);return}return()=>{onReadyRef.current?.(null);view.dispose();scene.current=null}},[retry])
 useEffect(()=>{let alive=true;setLoading(true);setError('');scene.current?.showBuild(build).then(()=>{if(alive)setLoading(false)}).catch(e=>{if(alive){setError(String(e));setLoading(false)}});return()=>{alive=false}},[build,retry])
 useEffect(()=>{scene.current?.setSettings(settings)},[settings])
 return <div className={`preview ${compact?'compact':''}`}><div ref={host} className="canvas-host"/>{loading&&!error&&<div className="canvas-status"><LoaderCircle className="spin" size={24}/><span>相棒を組み立てています</span></div>}{error&&<div className="canvas-status error"><p>{error}</p><button onClick={()=>setRetry(r=>r+1)}>再読み込み</button></div>}<div className="preview-caption"><span className="live-dot"/> LIVE 3D PREVIEW</div><div className="view-controls"><button title="斜めから" aria-label="斜めから見る" onClick={()=>scene.current?.cameraView('iso')}><Box size={17}/></button><button title="正面から" aria-label="正面から見る" onClick={()=>scene.current?.cameraView('front')}><Scan size={17}/></button><button title="真上から" aria-label="真上から見る" onClick={()=>scene.current?.cameraView('top')}><ArrowUp size={17}/></button><button title="横から" aria-label="横から見る" onClick={()=>scene.current?.cameraView('side')}><RotateCcw size={17}/></button></div><span className="drag-hint">ドラッグで回転 · スクロールで拡大</span></div>
}
export function EmptyState({children}:{children:ReactNode}){return <div className="empty-state">{children}</div>}
