import { ArrowRight, Bot, Users, FlaskConical, Flag, Map, Trophy, Swords, Play, RotateCcw, Pencil, Check } from 'lucide-react'
import { CHALLENGES, CPU_BUILDS, STAGES, TOURS } from '../game/catalog'
import { getAssemblyStats } from '../game/equipment'
import type { Build, Difficulty, GameMode, StageDef } from '../game/types'
import type { RecordBook } from '../game/storage'

export interface Entrant { name:string;cpu:boolean;build:Build }
export interface Tournament { round:number;waiting:Entrant[];winners:Entrant[];history:[string,string,string][];champion?:Entrant;pendingWinner?:Entrant }
const modes=[{id:'cpu',name:'CPUと対戦',caption:'相手を選んで、ひと勝負。',icon:Bot},{id:'local',name:'ふたりで対戦',caption:'同じ端末で、交互に。',icon:Users},{id:'practice',name:'練習・実験場',caption:'試して、戻して、発見しよう。',icon:FlaskConical},{id:'challenge',name:'技のチャレンジ',caption:'ひらめきの一手を磨こう。',icon:Flag},{id:'tour',name:'放課後ツアー',caption:'6人の文房具使いに挑む。',icon:Map},{id:'tournament',name:'ローカル大会',caption:'4人・8人の勝ち抜き戦。',icon:Trophy},{id:'team',name:'2対2チーム戦',caption:'味方と一緒に、机を制覇。',icon:Swords}]
export function Setup({build,secondBuild,mode,setMode,stage,setStage,difficulty,setDifficulty,opponent,setOpponent,first,setFirst,onStart,onContinue,canContinue,onEditSecond,record,entrants,setEntrants,tournament,onTournamentContinue,onTourReset}:{build:Build;secondBuild:Build;mode:GameMode;setMode:(m:GameMode)=>void;stage:StageDef;setStage:(s:StageDef)=>void;difficulty:Difficulty;setDifficulty:(d:Difficulty)=>void;opponent:number;setOpponent:(i:number)=>void;first:string;setFirst:(s:string)=>void;onStart:(challengeId?:string)=>void;onContinue:()=>void;canContinue:boolean;onEditSecond:()=>void;record:RecordBook;entrants:Entrant[];setEntrants:(e:Entrant[])=>void;tournament:Tournament|null;onTournamentContinue:()=>void;onTourReset:()=>void}){
 const selectedMode=modes.find(m=>m.id===mode)??modes[0],stats=getAssemblyStats(build)
 return <div className="setup-page page-enter"><div className="page-heading"><div><div className="eyebrow">THE DESK IS YOUR ARENA</div><h1>放課後の、<span>真剣勝負。</span></h1><p>押し出したら勝ち。考える時間は、いくらでも。</p></div>{canContinue&&<button className="button" onClick={onContinue}><Play size={17}/> 続きからあそぶ</button>}</div><div className="mode-grid">{modes.map(m=><button className={`mode-card ${mode===m.id?'selected':''}`} key={m.id} onClick={()=>setMode(m.id as GameMode)}><m.icon size={24}/><strong>{m.name}</strong><span>{m.caption}</span>{mode===m.id&&<i><Check size={13}/></i>}</button>)}</div>
 {mode==='challenge'?<><div className="section-intro"><h2>できるまで、何度でも。</h2><p>回数と時間に制限はありません。技を決めたらクリア。</p></div><div className="challenge-grid">{CHALLENGES.map((challenge,i)=><button className="panel challenge-card" key={challenge.id} onClick={()=>onStart(challenge.id)}><span className="challenge-no">0{i+1}</span><h3>{challenge.name}</h3><p>{challenge.description}</p><span className={record.challenges.includes(challenge.id)?'tag green':'tag'}>{record.challenges.includes(challenge.id)?'✓ クリア済み':'この技に挑戦 →'}</span></button>)}</div></>:mode==='tour'?<><div className="tour-path">{TOURS.map((tour,i)=><article className={`panel tour-card ${i<record.tour?'complete':''} ${i===record.tour?'current':''}`} key={tour.name}><img src={`/icons/body_${tour.build.body}.png`} alt=""/><span className="mini-label">STOP {i+1}</span><h3>{tour.name}</h3><p>{tour.description}</p><small>{tour.build.equipment.map(e=>e.id).map(id=>id.replace('_',' ')).join(' ＋ ')}</small><span className="tag">{i<record.tour?'✓ クリア':i===record.tour?'次の相手':'この先の相手'}</span></article>)}</div><div className="setup-start"><p>ボスも同じルール。装備はふたつ、時間制限なし。</p>{record.tour<TOURS.length?<button className="button primary large" onClick={()=>onStart()}>ツアーを{record.tour?'続ける':'はじめる'} <ArrowRight size={19}/></button>:<button className="button primary" onClick={onTourReset}><RotateCcw size={18}/> ツアーをもう一度</button>}</div></>:<>
 {mode==='tournament'&&<div className="tournament-setup panel"><div className="parts-heading"><div><h2>参加者を決めよう</h2><p>人間とCPUを自由に組み合わせられます。</p></div><select aria-label="大会の参加人数" value={entrants.length} onChange={e=>{const n=Number(e.target.value);setEntrants(Array.from({length:n},(_,i)=>entrants[i]??{name:`プレイヤー${i+1}`,cpu:i>0,build:structuredClone(CPU_BUILDS[i%6])}))}}><option value="4">4人</option><option value="8">8人</option></select></div><div className="entrants-grid">{entrants.map((e,i)=><div className="entrant-row" key={i}><b>{i+1}</b><input aria-label={`参加者${i+1}の名前`} value={e.name} maxLength={18} onChange={ev=>setEntrants(entrants.map((p,n)=>n===i?{...p,name:ev.target.value}:p))}/><select aria-label={`参加者${i+1}の種類`} value={e.cpu?'cpu':'human'} onChange={ev=>setEntrants(entrants.map((p,n)=>n===i?{...p,cpu:ev.target.value==='cpu'}:p))}><option value="human">人間</option><option value="cpu">CPU</option></select><select aria-label={`参加者${i+1}の機体`} value={e.build.name===build.name?'mine':Math.max(0,CPU_BUILDS.findIndex(b=>b.name===e.build.name))} onChange={ev=>setEntrants(entrants.map((p,n)=>n===i?{...p,build:structuredClone(ev.target.value==='mine'?build:CPU_BUILDS[Number(ev.target.value)])}:p))}><option value="mine">マイ消しゴム</option>{CPU_BUILDS.map((b,j)=><option key={b.name} value={j}>{b.name}</option>)}</select></div>)}</div>{tournament&&<div className="tournament-progress"><h3>{tournament.champion?`優勝：${tournament.champion.name}`:`保存した大会 · ラウンド${tournament.round}`}</h3>{tournament.history.map((match,i)=><p key={i}>{match[0]} <span>vs.</span> {match[1]} <strong>→ {match[2]}</strong></p>)}{!tournament.champion&&<button className="button" onClick={onTournamentContinue}>大会の続きから</button>}</div>}</div>}
 <div className="match-options"><div className="panel opponent-panel"><div className="section-label"><span>01</span><h2>{mode==='local'?'対戦するふたり':mode==='team'?'チームの準備':'対戦の準備'}</h2></div><div className="match-builds"><div><img src={`/icons/body_${build.body}.png`} alt=""/><span className="mini-label">YOU</span><h3>{build.name}</h3><p>重さ {Math.round(stats.mass*24)}g / 幅 {stats.width.toFixed(1)}</p></div><b>VS</b><div><img src={`/icons/body_${(mode==='local'?secondBuild:CPU_BUILDS[opponent]).body}.png`} alt=""/><span className="mini-label">{mode==='local'?'PLAYER 2':'OPPONENT'}</span>{mode==='local'?<><h3>{secondBuild.name}</h3><button className="text-button" onClick={onEditSecond}><Pencil size={13}/> 機体をカスタム</button></>:<select aria-label="CPUの相手" value={opponent} onChange={e=>setOpponent(Number(e.target.value))}>{CPU_BUILDS.map((b,i)=><option value={i} key={b.name}>{b.name}</option>)}</select>}</div></div><div className="form-row"><label className="form-field">CPUの難易度<select value={difficulty} onChange={e=>setDifficulty(e.target.value as Difficulty)}><option value="easy">やさしい</option><option value="normal">ふつう</option><option value="hard">つよい</option></select></label><label className="form-field">最初の手番<select value={first} onChange={e=>setFirst(e.target.value)}><option value="random">ランダム</option><option value="0">プレイヤー1</option><option value="1">プレイヤー2 / CPU</option></select></label></div>{mode==='practice'&&<p className="note">練習場では両方の消しゴムを操作できます。1回前に戻す・リプレイ・予測表示を使って実験しよう。</p>}{mode==='team'&&<p className="note">P1とCPUの相棒 vs CPUふたり。生き残った味方で続けられます。</p>}</div><div className="selected-stage-panel" style={{'--stage-color':stage.color} as React.CSSProperties}><div className="stage-decoration"><div className="mini-arena">{stage.objects.slice(0,10).map(o=><i key={o.id} style={{left:`${50+o.position.x*3}%`,top:`${50+o.position.z*3}%`,width:`${o.size.x*3}%`,height:`${o.size.z*3}%`,background:o.color??(o.kind==='desk'?'#dfbc8b':'#9abbb0'),transform:`translate(-50%,-50%) rotate(${-(o.rotation??0)}rad)`}}/>) }<span className="mini-eraser one"/><span className="mini-eraser two"/></div></div><span className="tag">{stage.difficulty}</span><h2>{stage.name}</h2><p>{stage.description}</p></div></div><div className="section-intro"><h2>今日の机を選ぼう。</h2><p>場所が変われば、戦い方も変わる。</p></div><div className="stage-grid">{STAGES.map((s,i)=><button className={`stage-card ${stage.id===s.id?'selected':''}`} key={s.id} onClick={()=>setStage(s)}><span style={{background:`${s.color}30`,color:s.color}}>{String(i+1).padStart(2,'0')}</span><div><strong>{s.name}</strong><small>{s.subtitle}</small></div>{stage.id===s.id&&<Check size={16}/>}</button>)}</div><div className="setup-start"><p>勝敗はリングアウトだけ。何手でも、何分でも、好きなだけ。</p><button className="button primary large" onClick={()=>onStart()}>{selectedMode.name}をはじめる <ArrowRight size={20}/></button></div></>}
 </div>
}
