import { useRef, useState } from 'react'
import { ArrowRight, ArrowUpRight, Plus, X, Search, Shuffle, Bookmark, Download, Upload, Copy, Trash2, Check, Scale, Sparkles, ChevronDown, FlaskConical, Palette, Heart } from 'lucide-react'
import { BODIES, PARTS, COMBOS, SOCKET_LABELS } from '../game/catalog'
import { getAssemblyStats, validateBuild } from '../game/equipment'
import { exportBuild, importBuild, loadFavorites, save } from '../game/storage'
import { audio } from '../game/audio'
import { Modal, Preview } from './common'
import type { Build, Equipment, PartDef, Settings, Socket } from '../game/types'
import { assetUrl } from '../game/assets'

const sleeveColors=['#369f88','#dcac60','#739cc5','#d48997','#605d83','#ec7c56']
export function Workshop({build,onChange,settings,onPlay,onPractice,notify}:{build:Build;onChange:(b:Build)=>void;settings:Settings;onPlay:()=>void;onPractice:()=>void;notify:(s:string)=>void}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('すべて'),[replacement,setReplacement]=useState<PartDef|null>(null),[details,setDetails]=useState<PartDef|null>(null),[cosmetics,setCosmetics]=useState(false),[favoritesOpen,setFavoritesOpen]=useState(false),[favorites,setFavorites]=useState(loadFavorites)
 const file=useRef<HTMLInputElement>(null)
 const body=BODIES.find(b=>b.id===build.body)!,stats=getAssemblyStats(build),combo=COMBOS.find(c=>c.ids.every(id=>build.equipment.some(e=>e.id===id)))
 const categories=['すべて',...new Set(PARTS.map(p=>p.category))]
 const visible=PARTS.filter(p=>(filter==='すべて'||p.category===filter)&&(!query||`${p.name}${p.description}${p.tactic}`.includes(query)))
 function change(next:Build,sound='attach'){try{const valid=validateBuild(next);onChange(valid);audio.play(sound)}catch(e){notify(e instanceof Error?e.message:String(e))}}
 function add(part:PartDef,index?:number){if(index===undefined&&build.equipment.length===2){setReplacement(part);return}const equipment=build.equipment.map(e=>({...e}));const others=equipment.filter((_,i)=>i!==index);const choices=part.sockets.filter(socket=>!others.some(e=>e.socket===socket));for(const socket of choices){const entry:Equipment={id:part.id,socket,rotation:0};const attempt=[...equipment];if(index!==undefined)attempt[index]=entry;else attempt.push(entry);try{const next=validateBuild({...build,equipment:attempt});onChange(next);audio.play('attach');setReplacement(null);return}catch{}}notify('この配置では装備が重なります。別の位置へ動かすか、パーツを外してください。')}
 function random(){const a=PARTS[Math.floor(Math.random()*PARTS.length)],b=PARTS[Math.floor(Math.random()*PARTS.length)];change({...build,equipment:[{id:a.id,socket:'front',rotation:0},{id:b.id,socket:'back',rotation:0}]});notify('新しい組み合わせを発見しよう。')}
 function storeFavorite(){const next=[...favorites,structuredClone(build)].slice(-40);setFavorites(next);if(save('favorites',next)){audio.play('save');notify('お気に入りに保存しました。')}else notify('保存できませんでした。ブラウザの設定を確認してください。')}
 return <div className="workshop page-enter">
  <div className="page-heading"><div><div className="eyebrow"><span/> AFTER SCHOOL, ANYTHING IS POSSIBLE.</div><h1>今日の相棒を、<span>つくろう。</span></h1><p>消しゴムひとつ。文房具ふたつ。きみだけの戦い方。</p></div><button className="button primary large" onClick={onPlay}>この機体であそぶ <ArrowRight size={20}/></button></div>
  <div className="workshop-grid">
   <aside className="body-panel panel"><div className="section-label"><span>01</span><h2>消しゴムを選ぼう</h2></div><div className="body-options">{BODIES.map(b=><button key={b.id} className={`body-choice ${b.id===build.body?'selected':''}`} onClick={()=>change({...build,body:b.id},'body')} title={b.description}><img src={assetUrl(`/icons/body_${b.id}.png`)} alt=""/><span>{b.name}</span>{b.id===build.body&&<i><Check size={11}/></i>}</button>)}</div><div className="body-summary"><div className="tag">{body.subtitle}</div><h3>{body.name}</h3><p>{body.description}</p></div><div className="color-row"><span>スリーブの色</span><div>{sleeveColors.map(color=><button className={`swatch ${build.sleeve===color?'active':''}`} key={color} style={{background:color}} aria-label={`スリーブ色 ${color}`} onClick={()=>change({...build,sleeve:color},'color')}>{build.sleeve===color&&<Check size={13}/>}</button>)}</div></div><button className="text-button customize-more" onClick={()=>setCosmetics(true)}><Palette size={15}/> 名前・顔・カラーを変える <ArrowUpRight size={14}/></button></aside>
   <section className="model-panel"><div className="model-name"><span>MY ERASER</span><strong>{build.name}</strong><button className="icon-button" aria-label="お気に入りに保存" onClick={storeFavorite}><Heart size={18}/></button></div><Preview build={build} settings={settings}/><div className="preview-bottom"><div><span className="mini-label">ASSEMBLY NO. 001</span><span className="tiny-dot"/> {build.equipment.length===0?'身軽な、すっぴんスタイル':combo?.name??'オリジナルカスタム'}</div><button className="pill-button" onClick={onPractice}><FlaskConical size={15}/> ちょっと試す <ArrowUpRight size={14}/></button></div></section>
   <aside className="equipment-panel panel"><div className="section-label"><span>02</span><h2>ふたつの相棒</h2><b>{build.equipment.length}<small> / 2</small></b></div><p className="muted tiny">何も付けなくても、ひとつだけでもOK。</p><div className="equipped-list">{[0,1].map(index=>{const e=build.equipment[index],part=e?PARTS.find(p=>p.id===e.id):undefined;return <div className={`equipped-slot ${!part?'empty':''}`} key={index}>{part&&e?<><div className="slot-top"><span className="slot-num">0{index+1}</span><img src={part.icon} alt=""/><div><span>{part.category}</span><h3>{part.shortName}</h3></div><button aria-label={`${part.name}を外す`} className="icon-button" onClick={()=>change({...build,equipment:build.equipment.filter((_,i)=>i!==index)},'detach')}><X size={15}/></button></div><div className="slot-selects"><label><select aria-label={`装備${index+1}の位置`} value={e.socket} onChange={ev=>change({...build,equipment:build.equipment.map((p,i)=>i===index?{...p,socket:ev.target.value as Socket}:p)})}>{part.sockets.map(socket=><option key={socket} value={socket}>{SOCKET_LABELS[socket]}</option>)}</select><ChevronDown size={12}/></label><label><select aria-label={`装備${index+1}の向き`} value={e.rotation} onChange={ev=>change({...build,equipment:build.equipment.map((p,i)=>i===index?{...p,rotation:Number(ev.target.value)}:p)})}>{[0,90,180,270].map(r=><option key={r} value={r}>{r}°</option>)}</select><ChevronDown size={12}/></label></div></>:<><Plus size={22}/><span>下のパーツから選ぼう</span><small>SLOT 0{index+1}</small></>}</div>})}</div><div className="assembly-stats"><div><span><Scale size={14}/> 重さ</span><strong>{Math.round(stats.mass*24)}<small> g</small></strong></div><div className="stat-meter"><span>すべりやすさ</span><div><i style={{width:`${Math.max(8,Math.min(100,(1-stats.friction)*100))}%`}}/></div></div><div className="stat-meter"><span>はねやすさ</span><div><i style={{width:`${Math.max(8,stats.restitution*100)}%`}}/></div></div><p>機体幅 {stats.width.toFixed(1)} · 重心 {stats.center.y.toFixed(2)}</p></div>{combo?<div className="combo-note"><Sparkles size={17}/><div><strong>{combo.name}</strong><p>{combo.description}</p></div></div>:<div className="combo-note"><Sparkles size={17}/><p>パーツの形と重さで、動きが変わる。自由に組み合わせてみよう。</p></div>}</aside>
  </div>
  <section className="parts-section"><div className="parts-heading"><div><div className="section-label"><span>03</span><h2>文房具を、武器にしよう。</h2><em>ALL {PARTS.length} PARTS</em></div><p>好きなパーツをタップして装備。最初から、すべて使えます。</p></div><div className="library-actions"><button className="button small" onClick={random}><Shuffle size={15}/> おまかせ</button><button className="button small" onClick={()=>setFavoritesOpen(true)}><Bookmark size={15}/> お気に入り</button><button className="icon-button" aria-label="機体をJSONに書き出す" onClick={()=>exportBuild(build)}><Download size={17}/></button><button className="icon-button" aria-label="機体JSONを読み込む" onClick={()=>file.current?.click()}><Upload size={17}/></button><input type="file" hidden ref={file} accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{change(importBuild(await f.text()));notify('機体を読み込みました。')}catch(err){notify(String(err))}e.target.value=''}}/></div></div><div className="parts-toolbar"><div className="category-tabs">{categories.map(category=><button className={filter===category?'active':''} key={category} onClick={()=>setFilter(category)}>{category}</button>)}</div><label className="search-field"><Search size={16}/><input aria-label="パーツを検索" placeholder="パーツをさがす" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="parts-grid">{visible.map(part=><article className={`part-card ${build.equipment.some(e=>e.id===part.id)?'equipped':''}`} key={part.id}><button className="part-add" onClick={()=>add(part)} aria-label={`${part.name}を装備`}><div className="part-image" style={{background:`${part.color}15`}}><img src={part.icon} alt={part.name} loading="lazy"/><span>{build.equipment.some(e=>e.id===part.id)?<Check size={14}/>:<Plus size={14}/>}</span></div><div className="part-copy"><span>{part.category}</span><h3>{part.shortName}</h3><p>{part.description}</p></div></button><button className="part-details" onClick={()=>setDetails(part)}>使い方を見る <ArrowUpRight size={12}/></button></article>)}</div>{visible.length===0&&<p className="empty-state">見つかりませんでした。別の名前でさがしてみよう。</p>}</section>
  <div className="workshop-footer"><span>✦ うまくいかなくても、何度でも。放課後は、まだまだこれから。</span><button className="text-button" onClick={()=>change({...build,equipment:[]},'detach')}>装備をすべて外す</button></div>
  {replacement&&<Modal title="どちらのパーツと交換する？" onClose={()=>setReplacement(null)}><p className="modal-description">装備できるのは、合わせてふたつまで。{replacement.name}を付ける場所を選ぼう。</p><div className="replacement-list">{build.equipment.map((e,i)=>{const p=PARTS.find(p=>p.id===e.id)!;return <button key={i} className="button" onClick={()=>add(replacement,i)}><img src={p.icon} alt=""/> {p.name}<ArrowRight size={17}/></button>})}</div></Modal>}
  {details&&<Modal title={details.name} onClose={()=>setDetails(null)}><div className="detail-hero" style={{background:`${details.color}18`}}><img src={details.icon} alt={details.name}/></div><p>{details.description}</p><dl className="detail-list"><dt>得意なこと</dt><dd>{details.tactic}</dd><dt>弱点</dt><dd>{details.weakness}</dd><dt>物理設定</dt><dd>重さ {Math.round(details.mass*24)} g · 摩擦 {details.friction} · 反発 {details.restitution}</dd></dl><button className="button primary full" onClick={()=>{add(details);setDetails(null)}}><Plus size={17}/> このパーツを装備</button></Modal>}
  {cosmetics&&<Modal title="自分だけの消しゴムに" onClose={()=>setCosmetics(false)}><label className="form-field">機体の名前<input maxLength={18} value={build.name} onChange={e=>change({...build,name:e.target.value},'color')}/></label><div className="form-row"><label className="form-field">本体の色<input type="color" value={build.color} onChange={e=>change({...build,color:e.target.value},'color')}/></label><label className="form-field">スリーブの色<input type="color" value={build.sleeve} onChange={e=>change({...build,sleeve:e.target.value},'color')}/></label></div><label className="form-field">顔のステッカー<select value={build.face} onChange={e=>change({...build,face:e.target.value},'color')}><option value="happy">にこにこ</option><option value="simple">きょとん</option><option value="cool">クール</option><option value="none">顔なし</option></select></label><label className="form-field">スリーブの柄<select value={build.pattern} onChange={e=>change({...build,pattern:e.target.value},'color')}><option value="plain">シンプル</option><option value="dots">ドット</option><option value="stripes">ストライプ</option></select></label><p className="muted tiny">色・顔・名前を変えても、性能は変わりません。</p></Modal>}
  {favoritesOpen&&<Modal title="お気に入りの相棒" onClose={()=>setFavoritesOpen(false)} wide><button className="button primary" onClick={storeFavorite}><Plus size={16}/> 今の機体を保存する</button><div className="favorites-grid">{favorites.map((f,i)=><article className="favorite-card" key={i}><div className="favorite-thumb" style={{background:`${f.sleeve}20`}}><img src={assetUrl(`/icons/body_${f.body}.png`)} alt=""/></div><h3>{f.name}</h3><p>{f.equipment.map(e=>PARTS.find(p=>p.id===e.id)?.shortName).join(' ＋ ')||'装備なし'}</p><div><button className="button small" onClick={()=>{change(structuredClone(f));setFavoritesOpen(false)}}>使う</button><button className="icon-button" aria-label="複製する" onClick={()=>{const next=[...favorites,{...structuredClone(f),name:`${f.name.slice(0,14)}のコピー`}].slice(-40);setFavorites(next);save('favorites',next)}}><Copy size={15}/></button><button className="icon-button" aria-label="削除する" onClick={()=>{const next=favorites.filter((_,n)=>n!==i);setFavorites(next);save('favorites',next)}}><Trash2 size={15}/></button></div></article>)}</div>{favorites.length===0&&<p className="empty-state">気に入った組み合わせを、ここに集めよう。</p>}</Modal>}
 </div>
}
