import { useCallback, useEffect, useState } from 'react'
import { Eraser, SlidersHorizontal, Volume2, VolumeX, HelpCircle, Settings2, Sparkles, Gamepad2, BookOpen, Grid2X2, X, Check } from 'lucide-react'
import { Workshop } from './components/Workshop'
import { Setup } from './components/Setup'
import type { Entrant, Tournament } from './components/Setup'
import { Battle } from './components/Battle'
import { Collection } from './components/Collection'
import { StageEditor } from './components/StageEditor'
import { Modal } from './components/common'
import { BODIES, CHALLENGES, COMBOS, CPU_BUILDS, DEFAULT_BUILD, STAGES, TOURS } from './game/catalog'
import { validateBuild } from './game/equipment'
import { audio } from './game/audio'
import { EMPTY_RECORD, load, loadBuild, loadSettings, readBattle, removeSave, save } from './game/storage'
import type { RecordBook } from './game/storage'
import type { BattleConfig, BattleSnapshot, BattleView, Build, Difficulty, GameMode, Settings, StageDef } from './game/types'

export default function App(){
 const [tab,setTab]=useState('workshop'),[build,setBuild]=useState(()=>loadBuild(DEFAULT_BUILD)),[secondBuild,setSecondBuild]=useState<Build>(()=>({...structuredClone(DEFAULT_BUILD),name:'ともだちの相棒',sleeve:'#dd9b61'})),[editing,setEditing]=useState(0),[settings,setSettings]=useState(loadSettings),[modal,setModal]=useState<'help'|'settings'|null>(null),[toast,setToast]=useState(''),[mode,setMode]=useState<GameMode>('cpu'),[stage,setStage]=useState(STAGES[0]),[difficulty,setDifficulty]=useState<Difficulty>('normal'),[opponent,setOpponent]=useState(0),[first,setFirst]=useState('random'),[record,setRecord]=useState<RecordBook>(()=>({...EMPTY_RECORD,...load('record',EMPTY_RECORD)})),[battle,setBattle]=useState<{config:BattleConfig;snapshot?:BattleSnapshot;key:number}|null>(null),[canContinue,setCanContinue]=useState(()=>!!readBattle()),[tournament,setTournament]=useState<Tournament|null>(()=>load('tournament',null)),[entrants,setEntrants]=useState<Entrant[]>(()=>Array.from({length:4},(_,i)=>({name:i===0?'きみ':CPU_BUILDS[i-1].name,cpu:i>0,build:structuredClone(i===0?loadBuild(DEFAULT_BUILD):CPU_BUILDS[i-1])})))
 const notify=useCallback((message:string)=>setToast(message),[])
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4200);return()=>clearTimeout(timer)},[toast])
 useEffect(()=>{audio.setSettings(settings);save('settings',settings)},[settings])
 useEffect(()=>{save('record',record)},[record])
 useEffect(()=>{const unlock=()=>{void audio.unlock().catch(()=>notify('音声を開始できませんでした。設定から「音声を再開」を押してください。'))};window.addEventListener('pointerdown',unlock,{once:true});window.addEventListener('keydown',unlock,{once:true});const error=(e:Event)=>notify((e as CustomEvent<string>).detail);window.addEventListener('audio-error',error);return()=>{window.removeEventListener('pointerdown',unlock);window.removeEventListener('keydown',unlock);window.removeEventListener('audio-error',error)}},[notify])
 useEffect(()=>{if(!battle)audio.setMusic(tab==='collection'?'collection':tab==='setup'?'title':'customize')},[tab,battle])
 function changeBuild(next:Build){try{const valid=validateBuild(next);if(editing===0){setBuild(valid);if(!save('build',valid))notify('機体の保存ができませんでした。')}else setSecondBuild(valid)}catch(e){notify(String(e))}}
 function showTab(next:string){audio.play('select');setEditing(0);setTab(next)}
 function rememberUsed(config:BattleConfig){const used=new Set(record.used),combos=new Set(record.combos);config.players.forEach((p,i)=>{if(i!==0)return;p.build.equipment.forEach(e=>used.add(e.id));COMBOS.forEach(c=>{if(c.ids.every(id=>p.build.equipment.some(e=>e.id===id)))combos.add(c.name)})});setRecord(r=>({...r,used:[...used],combos:[...combos],achievements:used.size>=10?[...new Set([...r.achievements,'explorer'])]:r.achievements}))}
 function begin(config:BattleConfig,snapshot?:BattleSnapshot){rememberUsed(config);setBattle({config,snapshot,key:Date.now()});setCanContinue(true);void audio.unlock()}
 function configFor(which:GameMode,selectedStage=stage,enemy=CPU_BUILDS[opponent]):BattleConfig{return {stage:structuredClone(selectedStage),players:[{build:structuredClone(build),team:0,cpu:false,name:build.name},{build:structuredClone(which==='local'?secondBuild:enemy),team:1,cpu:!['local','practice','custom','challenge'].includes(which),name:which==='local'?secondBuild.name:enemy.name}],mode:which,difficulty,firstPlayer:which==='practice'||which==='custom'||which==='challenge'?0:first==='random'?Math.floor(Math.random()*2):Number(first),seed:crypto.getRandomValues(new Uint32Array(1))[0]}}
 function tournamentBattle(state:Tournament){if(state.champion){setTab('setup');return}const c=configFor('tournament');c.players=state.waiting.slice(0,2).map((e,i)=>({...e,team:i}));begin(c)}
 function start(challengeId?:string){if(mode==='tournament'){const state:Tournament={round:1,waiting:structuredClone(entrants),winners:[],history:[]};setTournament(state);save('tournament',state);tournamentBattle(state);return}if(mode==='tour'){const tour=TOURS[Math.min(record.tour,TOURS.length-1)];begin(configFor('tour',STAGES.find(s=>s.id===tour.stageId)!,tour.build));return}const c=configFor(mode)
  if(mode==='challenge'&&challengeId){const challenge=CHALLENGES.find(c=>c.id===challengeId)!;c.stage=structuredClone(STAGES.find(s=>s.id===challenge.stageId)!);c.challengeId=challenge.id;if(challenge.goal==='jump')c.players[0].build.equipment=[{id:'pen_cap',socket:'front',rotation:0},{id:'sticky_note',socket:'back',rotation:0}];if(challenge.goal==='surface')c.players[0].build.equipment=[{id:'chalk',socket:'front',rotation:0},{id:'glue_stick',socket:'back',rotation:0}];if(challenge.goal==='return')c.stage.spawns[0]={x:-9.5,y:.4,z:4};if(challenge.goal==='win')c.players[1].build=structuredClone(CPU_BUILDS[2])}
  if(mode==='team'){c.players.push({build:structuredClone(CPU_BUILDS[3]),cpu:true,team:0,name:'ミントの相棒'},{build:structuredClone(CPU_BUILDS[2]),cpu:true,team:1,name:'オレンジの相棒'});const a=c.stage.spawns[0],b=c.stage.spawns[1];c.stage.spawns=[{...a,z:-3.5},{...b,z:3.5},{...a,z:3.5},{...b,z:-3.5}]}
  begin(c)
 }
 function reportResult(view:BattleView){if(!battle)return;const c=battle.config;setRecord(r=>{const achievements=new Set(r.achievements);if(view.winner===0){achievements.add('first_win');if(c.players[0].build.equipment.length===0)achievements.add('bare_win');if(c.players[0].build.equipment.length===2&&c.players[0].build.equipment[0].id===c.players[0].build.equipment[1].id)achievements.add('double_win')}const nextTour=c.mode==='tour'&&view.winner===0?Math.min(TOURS.length,r.tour+1):r.tour;if(nextTour===TOURS.length)achievements.add('tour');return {...r,battles:r.battles+1,wins:r.wins+(view.winner===0?1:0),tour:nextTour,achievements:[...achievements]}});removeSave('battle');setCanContinue(false);if(c.mode==='tournament'&&view.winner!==null&&tournament){const winner=tournament.waiting[view.winner];const next={...tournament,pendingWinner:winner};setTournament(next);save('tournament',next)}}
 function nextTournament(){if(!tournament)return;if(!tournament.pendingWinner){tournamentBattle(tournament);return}const history:[string,string,string][]=[...tournament.history,[tournament.waiting[0].name,tournament.waiting[1].name,tournament.pendingWinner.name]],winners=[...tournament.winners,tournament.pendingWinner],waiting=tournament.waiting.slice(2);let next:Tournament={round:tournament.round,waiting,winners,history};if(waiting.length===0){if(winners.length===1){next.champion=winners[0];setBattle(null);setTab('setup');notify(`${winners[0].name}、優勝おめでとう！`)}else next={round:tournament.round+1,waiting:winners,winners:[],history}}setTournament(next);save('tournament',next);if(!next.champion)tournamentBattle(next)}
 function continueBattle(){const snapshot=readBattle();if(!snapshot){notify('再開できる対戦データがありません。');setCanContinue(false);return}begin(snapshot.config,snapshot)}
 function finishBattle(){const previous=battle?.config;setBattle(null);setCanContinue(!!readBattle());setTab(previous?.mode==='custom'?'editor':previous?.mode==='practice'?'workshop':'setup')}
 const closeModal=useCallback(()=>setModal(null),[])
 return <><header className="app-header"><a className="brand" href="#" onClick={e=>{e.preventDefault();if(battle)finishBattle();showTab('workshop')}}><div className="brand-mark"><Eraser size={27} strokeWidth={2.3}/></div><div><strong>消しバト<span>！</span></strong><small>放課後カスタムアリーナ</small></div></a><nav aria-label="メインメニュー">{[{id:'setup',label:'あそぶ',icon:Gamepad2},{id:'workshop',label:'マイ消しゴム',icon:SlidersHorizontal},{id:'collection',label:'図鑑・コレクション',icon:BookOpen},{id:'editor',label:'ステージ工房',icon:Grid2X2}].map(item=><button className={!battle&&tab===item.id?'active':''} key={item.id} onClick={()=>{if(battle){notify('対戦画面の戻るボタンから、保存してメニューへ戻れます。');return}showTab(item.id)}}><item.icon size={16}/><span>{item.label}</span></button>)}</nav><div className="header-actions"><span className="offline-badge"><span/> いつでも、好きなだけ。</span><button className="icon-button" aria-label={settings.muted?'音をオン':'音をミュート'} onClick={()=>setSettings({...settings,muted:!settings.muted})}>{settings.muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><button className="icon-button" aria-label="あそびかた" onClick={()=>setModal('help')}><HelpCircle size={19}/></button><button className="icon-button" aria-label="設定" onClick={()=>setModal('settings')}><Settings2 size={19}/></button></div></header>
 <main className={battle?'main battle-main':'main'}>{battle?<Battle key={battle.key} config={battle.config} snapshot={battle.snapshot} settings={settings} onExit={finishBattle} onRematch={()=>{const c=structuredClone(battle.config);c.firstPlayer=(c.firstPlayer+1)%c.players.length;if(c.mode==='tournament'&&tournament){const next={...tournament,pendingWinner:undefined};setTournament(next);save('tournament',next)}begin(c)}} onResult={reportResult} onChallenge={id=>setRecord(r=>({...r,challenges:[...new Set([...r.challenges,id])],achievements:[...new Set([...r.achievements,'challenge'])]}))} onAdvance={battle.config.mode==='tournament'?nextTournament:battle.config.mode==='tour'?()=>{if(record.tour>=TOURS.length)finishBattle();else start()}:undefined} advanceLabel={battle.config.mode==='tour'?'次の教室へ':'勝ち抜き表を進める'} notify={notify}/>:tab==='workshop'?<>{editing===1&&<div className="editing-banner">プレイヤー2の機体をカスタマイズ中 <button onClick={()=>{setEditing(0);setTab('setup')}}>準備画面へもどる →</button></div>}<Workshop build={editing===0?build:secondBuild} onChange={changeBuild} settings={settings} onPlay={()=>setTab('setup')} onPractice={()=>begin(configFor('practice'))} notify={notify}/></>:tab==='setup'?<Setup build={build} secondBuild={secondBuild} mode={mode} setMode={setMode} stage={stage} setStage={setStage} difficulty={difficulty} setDifficulty={setDifficulty} opponent={opponent} setOpponent={setOpponent} first={first} setFirst={setFirst} onStart={start} onContinue={continueBattle} canContinue={canContinue} onEditSecond={()=>{setEditing(1);setTab('workshop')}} record={record} entrants={entrants} setEntrants={setEntrants} tournament={tournament} onTournamentContinue={nextTournament} onTourReset={()=>{setRecord(r=>({...r,tour:0}));notify('ツアーを最初から楽しめます。')}}/>:tab==='collection'?<Collection build={build} settings={settings} record={record} onUse={b=>{setEditing(0);setBuild(validateBuild(b));save('build',b);setTab('workshop')}}/>:<StageEditor onTest={s=>begin(configFor('custom',s))} notify={notify}/>}</main>
 {!battle&&<footer className="app-footer"><span>HŌKAGO STATIONERY CLUB</span><span>小さな机に、大きな作戦。 <Sparkles size={12}/></span><button onClick={()=>setModal('help')}>あそびかた</button></footer>}
 {toast&&<div className="toast" role="status"><Check size={18}/><span>{toast}</span><button aria-label="通知を閉じる" onClick={()=>setToast('')}><X size={15}/></button></div>}
 {modal==='help'&&<Modal title="あそびかた" onClose={closeModal}><div className="help-steps"><div><b>01</b><h3>自分だけの相棒をつくる</h3><p>消しゴムに、好きな文房具を最大2個。0個でも1個でも遊べます。位置を変えると重心や当たり方も変わります。</p></div><div><b>02</b><h3>引っぱって、はなす</h3><p>自分の消しゴムから飛ばしたい方向と逆へドラッグ。引いた長さで強さが変わります。考える時間は無制限です。</p></div><div><b>03</b><h3>相手を机から落とそう</h3><p>動きが止まったら次の人の番。相手だけが落ちたら勝ち、同じ発射で両方落ちたら引き分け。横転しても負けにはなりません。</p></div></div><div className="help-controls"><p><strong>PC：</strong>右ドラッグでカメラ回転、ホイールで拡大。矢印キーで方向・強さを調整し、Spaceまたは「弾く」で発射。Escで照準を解除。</p><p><strong>スマートフォン：</strong>1本指で引っぱって発射。カメラボタンで操作切り替え。2本指はカメラ専用です。</p><p>照準中に盤面は動きません。中断するときは保存して「続きから」。記録・設定・機体はこの端末に保存されます。</p></div></Modal>}
 {modal==='settings'&&<Modal title="あそぶ環境を整える" onClose={closeModal}><h3>サウンド</h3>{([['master','全体の音量'],['bgm','BGM'],['sfx','効果音'],['ambient','教室の環境音']] as const).map(([key,label])=><label className="volume-setting" key={key}><span>{label}</span><input type="range" min="0" max="1" step=".01" value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/><b>{Math.round(settings[key]*100)}</b></label>)}<label className="check-label"><input type="checkbox" checked={settings.muted} onChange={e=>setSettings({...settings,muted:e.target.checked})}/> ミュート</label><button className="text-button" onClick={()=>{audio.resume();notify('音声の再生を再開します。')}}>音声を再開</button><hr/><h3>画面と演出</h3><label className="form-field">画質<select value={settings.quality} onChange={e=>setSettings({...settings,quality:e.target.value as Settings['quality']})}><option value="high">きれい · 影あり</option><option value="low">軽量 · スマートフォン向け</option></select></label><label className="check-label"><input type="checkbox" checked={settings.particles} onChange={e=>setSettings({...settings,particles:e.target.checked})}/> 紙片と粒子の演出</label><label className="check-label"><input type="checkbox" checked={settings.reducedMotion} onChange={e=>{setSettings({...settings,reducedMotion:e.target.checked});document.documentElement.classList.toggle('reduced-motion',e.target.checked)}}/> UIの動きを減らす</label><p className="muted tiny">画質を変えても、物理のルールや強さは変わりません。</p></Modal>}
 </>
}
